name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '15 15 * * *'
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  test_backend:
    runs-on: ubuntu-latest

    container: python:3.9-slim

    services:
      postgres:
        image: postgres
        ports:
          - 5433:5433
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: library_db
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Packages PIP
        run: |
          cd library_back
          pip3 install -r requirements.txt

      - name: Migrate
        run: |
          cd library_back
          python manage.py makemigrations
          python manage.py migrate


      - name: Run tests
        run: |
          cd library_back
          python3 manage.py test
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: library_db
#  build:
#
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: write
#      id-token: write
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#        
#      - name: Docker Compose up
#        run: docker compose up -d
